---
# Settings: https://gethomepage.dev/configs/settings/
title: Homestack
theme: dark
color: slate
language: es
headerStyle: clean

layout:
  Infraestructura:
    style: row
    columns: 4
  Productividad:
    style: row
    columns: 3
  Marketing:
    style: row
    columns: 2
  Observabilidad:
    style: row
    columns: 3
